# Site settings
title: LU Blog
email: 603769201@qq.com
description: > # this means to ignore newlines until "baseurl:"
  LU's blog, record learning tips.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://luzhenhuan.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  a568665478

# Build settings
markdown: kramdown
